//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MegaCastings.DBLib
{
    using System;
    using System.Collections.Generic;
    
    public partial class Metier
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Metier()
        {
            this.OffreCastings = new HashSet<OffreCasting>();
        }
    
        public int Identifiant { get; set; }
        public string Nom { get; set; }
        public Nullable<int> IdentifiantDomaineMetier { get; set; }
    
        public virtual DomaineMetier DomaineMetier { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OffreCasting> OffreCastings { get; set; }
    }
}
