//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MegaCastings.DBLib
{
    using System;
    using System.Collections.Generic;
    
    public partial class OffreCasting
    {
        public int Identifiant { get; set; }
        public string Intitule { get; set; }
        public string Reference { get; set; }
        public Nullable<System.DateTime> DateDebut { get; set; }
        public string NombrePoste { get; set; }
        public string Localisation { get; set; }
        public string DescriptionPoste { get; set; }
        public string DescriptionProfil { get; set; }
        public string Contact { get; set; }
        public Nullable<int> IdentifiantClient { get; set; }
        public Nullable<int> IdentifiantDomaineMetier { get; set; }
        public Nullable<int> IdentifiantTypeContrat { get; set; }
        public Nullable<int> IdentifiantMetier { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual DomaineMetier DomaineMetier { get; set; }
        public virtual Metier Metier { get; set; }
        public virtual TypeContrat TypeContrat { get; set; }
    }
}
